import Image from "next/image";
import Link from "next/link";
import { MEDIA, PREVIEW } from "./config";
import { Arrow } from "./shell";

export const LANDSCAPE = [
  { slug: "palantir", name: "Palantir", field: "Operational AI", headline: "AI connected to operational decisions.", image: "optics.png", intro: "Palantir's Artificial Intelligence Platform connects models, enterprise data and workflows so teams can build applications, agents and automations.", detail: "Its public AIP materials describe tools for human approval, execution visibility and end-to-end evaluation. These are useful reference points when asking how an AI-enabled workflow becomes an operational action.", relevance: "Vraelis focuses on AI security in defense, critical infrastructure and robotics. Vraelis Contour starts at the model release boundary: what was approved, where it was approved to go and what the receiving service reports loading.", source: "https://www.palantir.com/platforms/aip/", sourceTitle: "Explore Palantir AIP", related: "/model-integrity", relatedTitle: "Model integrity at Vraelis" },
  { slug: "anduril", name: "Anduril", field: "Defense autonomy", headline: "Software connecting autonomous systems.", image: "robotics-hall.png", intro: "Anduril develops defense technology across air, land and sea. Its Lattice software connects systems and supports operational coordination.", detail: "The public Lattice SDK is an entry point for developers working with the Lattice ecosystem. It makes integration boundaries a concrete engineering topic: systems have different owners, software and operating requirements.", relevance: "Defense is one of Vraelis's company focus areas. A potential integration would need its own threat model, access agreement and verification work; this landscape entry describes public technology, not an existing Lattice integration.", source: "https://www.anduril.com/lattice/lattice-sdk", sourceTitle: "Explore the Lattice SDK", related: "/solutions/defense", relatedTitle: "Vraelis's defense focus" },
  { slug: "googledeepmind", name: "Google DeepMind", field: "Robotics research", headline: "AI that perceives and acts in the world.", image: "optics.png", intro: "Google DeepMind's Gemini Robotics work explores how models perceive, reason and interact with physical environments.", detail: "Robotics brings model behavior into contact with equipment and surroundings. Model evaluation, deployment controls and operating limits become distinct questions when outputs can affect a physical system.", relevance: "Vraelis Contour is a product direction for robotics suppliers and system integrators. Its release evidence is separate from a claim that a model is safe or robust against every manipulated input.", source: "https://deepmind.google/models/gemini-robotics/", sourceTitle: "Explore Gemini Robotics", related: "/guides/ai-security-evaluation", relatedTitle: "How we frame security evaluation" },
  { slug: "cloudflare", name: "Cloudflare", field: "Network and access security", headline: "Security at the connection boundary.", image: "infrastructure.png", intro: "Cloudflare One connects and protects workforces, applications, AI agents and infrastructure through its SASE and Zero Trust platform.", detail: "Its public materials describe identity-based access, network controls and data protection. Those controls are part of the surrounding security architecture that an AI-specific product must account for.", relevance: "A model release control operates alongside existing identity, network and endpoint controls. Vraelis's security scope needs to specify which boundary it checks and what remains the responsibility of the surrounding system.", source: "https://www.cloudflare.com/zero-trust/", sourceTitle: "Explore Cloudflare One", related: "/zero-trust", relatedTitle: "Machine authority at Vraelis" },
  { slug: "nvidia", name: "NVIDIA", field: "Edge AI compute", headline: "Compute where machines operate.", image: "robotics-hall.png", intro: "NVIDIA's Jetson platform provides embedded compute, modules and developer kits for robotics and edge AI applications.", detail: "Compute at the edge makes power, latency, connectivity and hardware support part of the deployment problem. A security control has to be measured in the environment where it will run.", relevance: "Vraelis's current private reference experiment runs with ONNX Runtime on CPU. Jetson support is not established by that experiment; a future edge integration would require platform-specific work and measurements.", source: "https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/", sourceTitle: "Explore NVIDIA Jetson", related: "/guides/operating-constraints", relatedTitle: "Operating constraints for AI security" },
] as const;

export function LandscapeRow() {
  return <section className="v7-landscape-row v7-wrap" aria-label="Explore the industry landscape"><p>Explore the AI and autonomy landscape</p><div>{LANDSCAPE.map(c => <Link href={`${PREVIEW}/landscape/${c.slug}`} key={c.slug} aria-label={`Read about ${c.name}`} data-wordmark={c.slug === "anduril" || c.slug === "googledeepmind"}><Image src={`${MEDIA}/marks/${c.slug}.svg`} alt="" width={28} height={28} /><span>{c.name}</span></Link>)}</div></section>;
}
export function LandscapePreview({ slug }: { slug?: string }) {
  const c = LANDSCAPE.find(c => c.slug === slug);
  if (!c) return <><section className="v7-hero v7-wrap"><p className="v7-eyebrow">Industry landscape</p><h1>AI, autonomy<br />and the systems around them.</h1><p className="v7-hero__intro">Explore public work across operational AI, robotics,<br className="v7-desktop-break" /> defense, network security and edge compute.</p></section><LandscapeRow /><div className="v7-landscape-index v7-wrap">{LANDSCAPE.map(c => <Link href={`${PREVIEW}/landscape/${c.slug}`} key={c.slug}><Image src={`${MEDIA}/${c.image}`} alt="Illustrative engineering environment." width={800} height={500} /><div><p className="v7-eyebrow">{c.field}</p><h2>{c.name}<Arrow diagonal /></h2><p>{c.headline}</p></div></Link>)}</div><p className="v7-landscape-note v7-wrap">These editorial references describe public work. They do not indicate a customer, partnership or integration relationship with Vraelis.</p></>;
  return <>
    <section className="v7-landscape-hero v7-wrap"><Link href={`${PREVIEW}/landscape`} className="v7-eyebrow">Industry landscape</Link><div className="v7-company-mark" data-wordmark={c.slug === "anduril" || c.slug === "googledeepmind"}><Image src={`${MEDIA}/marks/${c.slug}.svg`} alt="" width={32} height={32} /><span>{c.name}</span></div><h1>{c.headline}</h1><p>{c.intro}</p><a className="v7-button v7-button--secondary" href={c.source} target="_blank" rel="noreferrer">{c.sourceTitle}<Arrow diagonal /></a></section>
    <figure className="v7-landscape-image v7-wrap"><Image src={`${MEDIA}/${c.image}`} alt="Original illustration of engineering equipment; not a company facility or product." width={1672} height={941} priority /><figcaption>Illustrative engineering context · Original artwork</figcaption></figure>
    <section className="v7-landscape-story v7-wrap"><div><p className="v7-eyebrow">{c.field}</p><h2>The public work.</h2><p>{c.detail}</p><a className="v7-text-link" href={c.source} target="_blank" rel="noreferrer">Read the primary source<Arrow diagonal /></a></div><div><p className="v7-eyebrow">Vraelis’s focus</p><h2>The security question.</h2><p>{c.relevance}</p><Link className="v7-text-link" href={c.related}>{c.relatedTitle}<Arrow diagonal /></Link></div></section>
    <p className="v7-landscape-note v7-wrap">An editorial reference to public technology. No customer, partnership or endorsement relationship is implied. Sources reviewed October 8, 2026.</p><LandscapeRow />
  </>;
}
