// Licensed editorial context, not product evidence. See public/site/photography/CREDITS.md.
export const EDITORIAL_PHOTOGRAPHS = {
  robotAssembly: {"file": "editorial-robotAssembly", "w": 1280, "h": 853, "alt": "An industrial robot arm inside a manufacturing cell.", "author": "Diego Martinez", "id": "29320998"},
  instrumentControls: {"file": "editorial-instrumentControls", "w": 1280, "h": 854, "alt": "An engineer adjusting laboratory equipment.", "author": "ThisIsEngineering", "id": "3862631"},
  developerDesk: {"file": "editorial-developerDesk", "w": 1280, "h": 854, "alt": "A software developer working at a computer.", "author": "ThisIsEngineering", "id": "3861972"},
  networkLinks: {"file": "editorial-networkLinks", "w": 1280, "h": 852, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "2881233"},
  engineeringLaptop: {"file": "editorial-engineeringLaptop", "w": 1280, "h": 854, "alt": "A software developer working at a computer.", "author": "ThisIsEngineering", "id": "3862599"},
  laboratoryRoom: {"file": "editorial-laboratoryRoom", "w": 1280, "h": 853, "alt": "Equipment and workstations in an engineering laboratory.", "author": "Mike van Schoonderwalt", "id": "5506058"},
  softwareWorkstation: {"file": "editorial-softwareWorkstation", "w": 1280, "h": 854, "alt": "A software developer working at a computer.", "author": "Christina Morillo", "id": "1181676"},
  fiberPanel: {"file": "editorial-fiberPanel", "w": 1280, "h": 853, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "4486718"},
  programmerDesk: {"file": "editorial-programmerDesk", "w": 1280, "h": 853, "alt": "A software developer working at a computer.", "author": "cottonbro studio", "id": "6805152"},
  ethernetPorts: {"file": "editorial-ethernetPorts", "w": 1280, "h": 852, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "2881232"},
  codeReview: {"file": "editorial-codeReview", "w": 1280, "h": 854, "alt": "A software developer working at a computer.", "author": "ThisIsEngineering", "id": "3861951"},
  codeMonitor: {"file": "editorial-codeMonitor", "w": 1280, "h": 854, "alt": "A software developer working at a computer.", "author": "Lee Campbell", "id": "89724"},
  laptopDevelopment: {"file": "editorial-laptopDevelopment", "w": 1280, "h": 854, "alt": "A software developer working at a computer.", "author": "Christina Morillo", "id": "1181675"},
  laptopKeyboard: {"file": "editorial-laptopKeyboard", "w": 1280, "h": 853, "alt": "A software developer working at a computer.", "author": "cottonbro studio", "id": "5474295"},
  serverWorkstation: {"file": "editorial-serverWorkstation", "w": 1280, "h": 852, "alt": "Computer servers in a data center.", "author": "Brett Sayles", "id": "5092815"},
  networkPorts: {"file": "editorial-networkPorts", "w": 1280, "h": 852, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "4716292"},
  computeCabinets: {"file": "editorial-computeCabinets", "w": 1280, "h": 852, "alt": "Computer servers in a data center.", "author": "panumas nikhomkhai", "id": "17489163"},
  memoryModules: {"file": "editorial-memoryModules", "w": 1280, "h": 854, "alt": "Electronic components on a circuit board.", "author": "IT services EU", "id": "7596072"},
  ethernetLink: {"file": "editorial-ethernetLink", "w": 1280, "h": 853, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "4818711"},
  fiberConnections: {"file": "editorial-fiberConnections", "w": 1280, "h": 853, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "4373997"},
  robotReview: {"file": "editorial-robotReview", "w": 1280, "h": 854, "alt": "An engineer working with a robotic arm.", "author": "Pavel Danilyuk", "id": "8439008"},
  laboratoryDesks: {"file": "editorial-laboratoryDesks", "w": 1280, "h": 960, "alt": "Equipment and workstations in an engineering laboratory.", "author": "Ludovic Delot", "id": "18471531"},
  computeHardware: {"file": "editorial-computeHardware", "w": 1280, "h": 852, "alt": "Computer servers in a data center.", "author": "panumas nikhomkhai", "id": "17489153"},
  computeIndicators: {"file": "editorial-computeIndicators", "w": 1280, "h": 854, "alt": "Computer servers in a data center.", "author": "panumas nikhomkhai", "id": "17489157"},
  serverAisle: {"file": "editorial-serverAisle", "w": 1280, "h": 852, "alt": "Computer servers in a data center.", "author": "Brett Sayles", "id": "5480781"},
  networkSwitch: {"file": "editorial-networkSwitch", "w": 1280, "h": 853, "alt": "Network cables connected to equipment.", "author": "Brett Sayles", "id": "4280696"},
  boardTraces: {"file": "editorial-boardTraces", "w": 1280, "h": 851, "alt": "Electronic components on a circuit board.", "author": "Miguel Á. Padriñán", "id": "3520692"},
  processorDetail: {"file": "editorial-processorDetail", "w": 1280, "h": 853, "alt": "Electronic components on a circuit board.", "author": "Jakub Pabis", "id": "36169774"},
  benchSoldering: {"file": "editorial-benchSoldering", "w": 1280, "h": 853, "alt": "An engineer inspecting or repairing a circuit board.", "author": "ThisIsEngineering", "id": "3912983"},
  circuitRepair: {"file": "editorial-circuitRepair", "w": 1280, "h": 873, "alt": "An engineer inspecting or repairing a circuit board.", "author": "tnfeez desgin", "id": "10699355"},
  microscopeInspection: {"file": "editorial-microscopeInspection", "w": 1280, "h": 853, "alt": "An engineer inspecting or repairing a circuit board.", "author": "Multitech Institute", "id": "35157345"},
  boardTesting: {"file": "editorial-boardTesting", "w": 1280, "h": 853, "alt": "An engineer inspecting or repairing a circuit board.", "author": "Mikhail Nilov", "id": "9242898"},
  factoryAssembly: {"file": "editorial-factoryAssembly", "w": 1280, "h": 853, "alt": "Industrial machinery on a factory floor.", "author": "Hyundai Motor Group", "id": "19233057"},
  gridEquipment: {"file": "editorial-gridEquipment", "w": 1280, "h": 853, "alt": "Electrical equipment at a power substation.", "author": "Andy Coffie", "id": "30762645"},
  boardInspection: {"file": "editorial-boardInspection", "w": 1280, "h": 853, "alt": "An engineer inspecting or repairing a circuit board.", "author": "Mikhail Nilov", "id": "9242263"},
  labWorkstations: {"file": "editorial-labWorkstations", "w": 1280, "h": 815, "alt": "Equipment and workstations in an engineering laboratory.", "author": "Mike van Schoonderwalt", "id": "5506050"},
  computerMemory: {"file": "editorial-computerMemory", "w": 1280, "h": 853, "alt": "Electronic components on a circuit board.", "author": "Andrey Matveev", "id": "5554949"},
  processorBoard: {"file": "editorial-processorBoard", "w": 1280, "h": 853, "alt": "Electronic components on a circuit board.", "author": "Pok Rie", "id": "1432673"},
  electronicsWorkbench: {"file": "editorial-electronicsWorkbench", "w": 1280, "h": 854, "alt": "Electronic components and tools on a workbench.", "author": "ThisIsEngineering", "id": "19895784"},
  engineeringTeam: {"file": "editorial-engineeringTeam", "w": 1280, "h": 960, "alt": "Engineers working in an electronics laboratory.", "author": "khezez | خزاز", "id": "34007253"},
  releaseReview: {"file": "editorial-releaseReview", "w": 1920, "h": 1282, "alt": "An engineer working with a robotic arm.", "author": "Pavel Danilyuk", "id": "8438994"},
  circuitLayers: {"file": "editorial-circuitLayers", "w": 1920, "h": 1281, "alt": "Electronic components on a circuit board.", "author": "Júlio Riccó", "id": "18372332"},
  dataCenterAisle: {"file": "editorial-dataCenterAisle", "w": 1920, "h": 1280, "alt": "Computer servers in a data center.", "author": "Brett Sayles", "id": "4508751"},
  robotProduction: {"file": "editorial-robotProduction", "w": 1920, "h": 1440, "alt": "Industrial machinery on a factory floor.", "author": "Ludovic Delot", "id": "18471543"},
  runtimeServers: {"file": "editorial-runtimeServers", "w": 1920, "h": 1278, "alt": "Computer servers in a data center.", "author": "panumas nikhomkhai", "id": "17489152"},
  embeddedBoard: {"file": "editorial-embeddedBoard", "w": 1920, "h": 1280, "alt": "Electronic components on a circuit board.", "author": "Pok Rie", "id": "1432794"},
  releaseInspection: {"file": "editorial-releaseInspection", "w": 1920, "h": 1280, "alt": "An engineer inspecting or repairing a circuit board.", "author": "Mikhail Nilov", "id": "9242275"},
  boardComponents: {"file": "editorial-boardComponents", "w": 1920, "h": 1440, "alt": "Electronic components on a circuit board.", "author": "Djenz Van Eysendeyk", "id": "28675583"},
  communicationsRoof: {"file": "editorial-communicationsRoof", "w": 1920, "h": 1280, "alt": "Satellite dishes on a rooftop.", "author": "Andrew Patrick Photo", "id": "33893090"},
  hardwareReview: {"file": "editorial-hardwareReview", "w": 1920, "h": 1280, "alt": "An engineer inspecting or repairing a circuit board.", "author": "Mikhail Nilov", "id": "9242888"},
  electronicsResearch: {"file": "editorial-electronicsResearch", "w": 1920, "h": 1281, "alt": "An engineer inspecting or repairing a circuit board.", "author": "ThisIsEngineering", "id": "19895705"},
  substationNetwork: {"file": "editorial-substationNetwork", "w": 1920, "h": 1182, "alt": "Electrical equipment at a power substation.", "author": "Robert So", "id": "18468536"},
  windOperations: {"file": "editorial-windOperations", "w": 1920, "h": 1013, "alt": "Wind turbines in an open landscape.", "author": "Mikhail Nilov", "id": "8412772"},
  robotMotion: {"file": "editorial-robotMotion", "w": 1920, "h": 1280, "alt": "An industrial robot arm inside a manufacturing cell.", "author": "Freek Wolsink", "id": "34207369"},
  robotGripper: {"file": "editorial-robotGripper", "w": 1920, "h": 1282, "alt": "An industrial robot arm inside a manufacturing cell.", "author": "Pavel Danilyuk", "id": "8438865"},
  communicationsDishes: {"file": "editorial-communicationsDishes", "w": 1920, "h": 1280, "alt": "Satellite dishes on a rooftop.", "author": "Francesco Ungaro", "id": "8476867"},
  integrationWorkshop: {"file": "editorial-integrationWorkshop", "w": 1920, "h": 1280, "alt": "An engineer inspecting equipment in a workshop.", "author": "Mikhail Nilov", "id": "9242208"},
  embeddedInterfaces: {"file": "editorial-embeddedInterfaces", "w": 1920, "h": 1280, "alt": "Electronic components on a circuit board.", "author": "Craig Dennis", "id": "57007"},
  operationalCompute: {"file": "editorial-operationalCompute", "w": 1920, "h": 1278, "alt": "Computer servers in a data center.", "author": "panumas nikhomkhai", "id": "37730212"},
  platformEngineer: {"file": "editorial-platformEngineer", "w": 1920, "h": 1440, "alt": "A software developer working at a computer.", "author": "Zayed Hossain", "id": "36706459"},
} as const;
