import type { Metadata } from "next";

// One metadata system for design 06. The public embed no longer describes deployment verification or browser
// testing; it describes oversight for AI software agents. Preview routes stay noindex, but every value is
// real and inspectable. The 1200x630 Open Graph image is generated by opengraph-image.tsx and merged in by
// Next for the whole /dev-preview/v6 segment (do not set openGraph.images here, or it would override it).
export const V6_ORIGIN = "https://vraelis.com";

export function v6meta(o: {
  title: string;
  description: string;
  path: string; // clean production path this route will live at, e.g. "/platform"
  ogTitle?: string;
  ogDescription?: string;
  type?: "website" | "article";
  published?: string;
  modified?: string;
}): Metadata {
  const url = `${V6_ORIGIN}${o.path}`;
  const ogTitle = o.ogTitle ?? o.title;
  const ogDescription = o.ogDescription ?? o.description;
  return {
    title: o.title,
    description: o.description,
    alternates: { canonical: url },
    robots: { index: false, follow: false },
    openGraph: {
      type: o.type ?? "website",
      title: ogTitle,
      description: ogDescription,
      url,
      siteName: "Vraelis",
      ...(o.type === "article" && (o.published || o.modified)
        ? { publishedTime: o.published, modifiedTime: o.modified }
        : {}),
    },
    twitter: { card: "summary_large_image", title: ogTitle, description: ogDescription },
  };
}
