import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Vraelis",
  description: "The terms for using Vraelis.",
};

const UPDATED = "June 4, 2026";

function H({ children }: { children: React.ReactNode }) {
  return <h2 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(1.3rem,2.2vw,1.7rem)", letterSpacing: "-0.02em", color: "var(--fg-1)", margin: "2em 0 0.6em" }}>{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 15.5, lineHeight: 1.7, color: "var(--fg-2)", margin: "0 0 1em" }}>{children}</p>;
}
function List({ items }: { items: React.ReactNode[] }) {
  return (
    <ul style={{ margin: "0 0 1em", paddingLeft: 20, color: "var(--fg-2)", fontSize: 15.5, lineHeight: 1.7 }}>
      {items.map((it, i) => <li key={i} style={{ marginBottom: 6 }}>{it}</li>)}
    </ul>
  );
}

export default function TermsPage() {
  return (
    <section className="section">
      <div className="wrap" style={{ maxWidth: 760 }}>
        <p className="eyebrow">Legal</p>
        <h1 className="display" style={{ fontSize: "clamp(2rem,3.4vw,2.8rem)", marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontFamily: "var(--font-mono)", fontSize: 12.5, color: "var(--fg-4)", marginBottom: 28 }}>Last updated {UPDATED}</p>

        <P>These terms govern your use of Vraelis. By creating an account or using the service you agree to them. If you don't agree, don't use Vraelis.</P>

        <H>The service</H>
        <P>Vraelis is a tool that replies to your inbound leads with an AI assistant, follows up, books appointments, and can collect payments from your leads on your behalf via Stripe. Vraelis is the tool; you run your business.</P>

        <H>Eligibility</H>
        <P>You must be at least 18 and use Vraelis for a legitimate business. You're responsible for everything that happens under your account, including the messages the AI sends to your leads on your behalf.</P>

        <H>Acceptable use</H>
        <P>You agree not to use Vraelis to:</P>
        <List items={[
          "Send spam or unsolicited messages, or contact people you don't have a lawful basis or consent to contact. You are responsible for complying with anti-spam and communication laws (such as CAN-SPAM, TCPA, GDPR, and local equivalents).",
          "Send illegal, deceptive, harassing, hateful, or harmful content.",
          "Collect sensitive information you're not allowed to (card numbers, bank details, government IDs, health data) through the chat — the assistant is instructed not to, and you must not work around that.",
          "Abuse, reverse-engineer, overload, or disrupt the service.",
        ]} />

        <H>AI disclaimer</H>
        <P>Replies, follow-ups, and other outputs are generated by AI and may be inaccurate, incomplete, or inappropriate. You are responsible for reviewing what the assistant does on your behalf. Vraelis output is not legal, medical, financial, or professional advice, and you should not rely on it as such. We don't guarantee any result, response rate, booking, or revenue.</P>

        <H>Your business and your customers</H>
        <P>You are solely responsible for the services and products you sell, for fulfilling them, and for any refunds, disputes, taxes, or obligations to your own customers. Vraelis is not a party to the transactions between you and your customers — it only helps facilitate them.</P>

        <H>Payments, plans, and the revenue share</H>
        <List items={[
          "Plans are billed through Stripe or PayPal at the prices shown on our pricing page. Subscriptions renew until cancelled.",
          "Payments your leads make through Vraelis are processed via Stripe Connect. Vraelis automatically takes a percentage fee (the rate shown for your plan) as an application fee at the time of payment. You authorize this fee.",
          "By connecting payouts you also agree to Stripe's Connected Account Agreement. Standard payment-processing fees are deducted from your payout.",
          "You can cancel a plan anytime from your account or Stripe. See our Refund Policy for details.",
        ]} />

        <H>Intellectual property</H>
        <P>Vraelis owns the platform, software, and brand. You keep ownership of your business content and your data. You grant us the limited rights needed to run the service for you (for example, sending your business details and your leads' messages to our AI provider to generate replies).</P>

        <H>Disclaimer and limitation of liability</H>
        <P>Vraelis is provided "as is," without warranties of any kind. To the maximum extent allowed by law, Vraelis and its operators are not liable for indirect, incidental, or consequential damages, or for lost profits, revenue, leads, or data. Our total liability for any claim is limited to the amount you paid us in the three months before the claim.</P>

        <H>Termination</H>
        <P>You can stop using Vraelis anytime. We may suspend or terminate accounts that violate these terms or put the service, its users, or third parties at risk.</P>

        <H>Changes</H>
        <P>We may update these terms. We'll update the date above and, for significant changes, notify you. Continued use means you accept the update.</P>

        <H>Contact</H>
        <P><a href="mailto:help@vraelis.com" style={{ color: "var(--acc-deep)" }}>help@vraelis.com</a></P>
      </div>
    </section>
  );
}
