// One place that runs every gate and reports each command's OWN exit status.
//
// ── WHY THIS EXISTS ────────────────────────────────────────────────────────────────────────────────────
// Twice during this remediation a green result was reported for a command that had actually failed, and
// both times the cause was the same: the status that got read belonged to a DIFFERENT process than the one
// being tested.
//
//   npx tsc --noEmit | head            -> $? is head's status. head always succeeds. tsc's errors vanish.
//   printf "%s %s" "$(basename $1)" "$?" -> the command substitution runs FIRST and resets $?, so the
//                                           status printed is basename's, not the command's.
//
// Neither looks wrong. Both print 0. A test harness that can report success for a failing command is worse
// than no harness, because it converts "unverified" into "verified" without anyone lying.
//
// So: every gate here is spawned with spawnSync, and its `.status` is read from the returned object
// IMMEDIATELY, into a variable, before anything else runs. There is no shell, so there is no pipeline for
// a status to get lost in; there is no `$?`, so there is nothing for a substitution to clobber. The status
// that is printed is, structurally, the status of the process that was run.
//
// ── LINT IS NOT GREEN, AND THIS SAYS SO ────────────────────────────────────────────────────────────────
// The repository inherits 186 ESLint errors from before this work (scripts/lint-baseline.json, measured on
// main@f09d1bc7). This runner does NOT pretend otherwise. It fails the lint gate on a REGRESSION —
// totals above the baseline, or any single file gaining problems — and reports the inherited count as an
// explicit, unresolved number every time it runs.
//
// Usage:
//   npx tsx scripts/gates.ts                 run every gate
//   npx tsx scripts/gates.ts --quick         skip build and the Docker-backed suites
//   npx tsx scripts/gates.ts --write-baseline  re-measure the lint baseline (deliberate act; see below)
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const BASELINE = "scripts/lint-baseline.json";
const args = process.argv.slice(2);
const quick = args.includes("--quick");

type GateResult = { name: string; status: number; ok: boolean; note: string };
const results: GateResult[] = [];

/**
 * Run one command and capture ITS status.
 *
 * No shell, no pipe, no command substitution. `r.status` is read into `status` on the very next line,
 * before any other call could overwrite it.
 */
function run(name: string, cmd: string, cmdArgs: string[]): { status: number; out: string } {
  const r = spawnSync(cmd, cmdArgs, {
    encoding: "utf8", maxBuffer: 1 << 28, shell: process.platform === "win32",
  });
  const status = r.status ?? -1;
  const out = `${r.stdout ?? ""}${r.stderr ?? ""}`;
  return { status, out };
}

function gate(name: string, cmd: string, cmdArgs: string[], note = ""): number {
  process.stdout.write(`  running ${name} ...`);
  const { status } = run(name, cmd, cmdArgs);
  const ok = status === 0;
  results.push({ name, status, ok, note });
  process.stdout.write(`\r  ${ok ? "PASS" : "FAIL"}  ${name.padEnd(34)} exit=${status}${note ? `  ${note}` : ""}\n`);
  return status;
}

// ── The lint gate: measured against the baseline, never declared green ─────
type Baseline = { totals: { errors: number; warnings: number }; files: Record<string, { errors: number; warnings: number }> };

function lintGate(): void {
  const { status, out } = run("eslint", "npx", ["eslint", ".", "-f", "json"]);
  // eslint exits 1 when it finds errors, 2 on a config/crash. Only 2 means the gate itself is broken.
  if (status === 2 || !out.trim().startsWith("[")) {
    results.push({ name: "lint", status, ok: false, note: "eslint could not run" });
    console.log(`  FAIL  ${"lint".padEnd(34)} exit=${status}  eslint could not run`);
    return;
  }

  const rel = (p: string) => p.replace(/\\/g, "/").replace(/^.*?\/vraelis\//, "");
  const report = JSON.parse(out.slice(out.indexOf("["))) as {
    filePath: string; errorCount: number; warningCount: number;
  }[];
  let errors = 0, warnings = 0;
  const current: Record<string, { errors: number; warnings: number }> = {};
  for (const f of report) {
    if (!f.errorCount && !f.warningCount) continue;
    errors += f.errorCount; warnings += f.warningCount;
    current[rel(f.filePath)] = { errors: f.errorCount, warnings: f.warningCount };
  }

  if (args.includes("--write-baseline")) {
    writeFileSync(BASELINE, JSON.stringify({
      _comment: ["Regenerated by scripts/gates.ts --write-baseline. Do this deliberately, never to turn a red gate green."],
      measuredOn: "regenerated", measuredAt: new Date().toISOString().slice(0, 10),
      command: "npx eslint . -f json",
      totals: { errors, warnings, files: Object.keys(current).length }, files: current,
    }, null, 2) + "\n");
    console.log(`  baseline rewritten: ${errors} errors, ${warnings} warnings`);
    return;
  }

  if (!existsSync(BASELINE)) {
    results.push({ name: "lint", status: 1, ok: false, note: `no baseline at ${BASELINE}` });
    console.log(`  FAIL  ${"lint".padEnd(34)} no baseline at ${BASELINE}`);
    return;
  }
  const base = JSON.parse(readFileSync(BASELINE, "utf8")) as Baseline;

  const regressions: string[] = [];
  if (errors > base.totals.errors) regressions.push(`total errors ${errors} > baseline ${base.totals.errors}`);
  for (const [file, cur] of Object.entries(current)) {
    const b = base.files[file] ?? { errors: 0, warnings: 0 };
    if (cur.errors > b.errors) regressions.push(`${file}: errors ${b.errors} -> ${cur.errors}`);
    if (cur.warnings > b.warnings) regressions.push(`${file}: warnings ${b.warnings} -> ${cur.warnings}`);
  }

  const ok = regressions.length === 0;
  const note = ok
    ? `no regression; ${errors} inherited errors + ${warnings} warnings STILL OPEN (baseline ${base.totals.errors}/${base.totals.warnings})`
    : `${regressions.length} regression(s): ${regressions.slice(0, 3).join("; ")}`;
  results.push({ name: "lint (vs baseline)", status: ok ? 0 : 1, ok, note });
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${"lint (vs baseline)".padEnd(34)} ${note}`);
}

console.log("\n══ GATES ═══════════════════════════════════════════════════════════════");
console.log("  Every exit code below is the tested process's own, read from spawnSync");
console.log("  before anything else could overwrite it. No pipes, no $?, no shell.\n");

gate("typecheck", "npx", ["tsc", "--noEmit", "-p", "tsconfig.json"]);
lintGate();

const SUITES = [
  "paypal-tier-integrity", "oauth-callback-xss", "oauth-registry-hardening", "contact-auth-abuse",
  "phase2-tenant-money", "phase2-hardening", "phase2-corrections",
  "phase3-settings-authz", "phase3-oauth-identity", "phase4-assurance",
  "phase41-autopay", "phase41-docs", "phase41-cookie", "db-target-policy",
];
const DOCKER_SUITES = ["phase2-credit-concurrency", "phase3-payment-cap", "rls-preflight"];

for (const s of SUITES) gate(s, "npx", ["tsx", `scripts/${s}-verify.ts`]);
if (!quick) {
  for (const s of DOCKER_SUITES) gate(s, "npx", ["tsx", `scripts/${s}-verify.ts`], "needs Docker");
  gate("build", "npx", ["next", "build"]);
} else {
  console.log("  SKIP  (--quick) build and the Docker-backed suites");
}

console.log("\n── summary ──");
const failed = results.filter((r) => !r.ok);
for (const r of results) console.log(`  ${r.ok ? "PASS" : "FAIL"}  ${r.name.padEnd(34)} exit=${r.status}`);
console.log(`\n${results.length - failed.length}/${results.length} gates passed`);
if (failed.length) console.log(`FAILED: ${failed.map((f) => f.name).join(", ")}`);
console.log("\nNOTE: lint is NOT globally clean. The gate above enforces no-regression against an inherited");
console.log("      baseline; see LINT-BACKLOG.md for what remains and why.");
console.log("═════════════════════════════════════════════════════════════════════════\n");

process.exit(failed.length === 0 ? 0 : 1);
