import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { LOCALE_KEYS } from "../lib/i18n/locales";
const hash=createHash("sha256");
for(const locale of [...LOCALE_KEYS].filter(l=>l!=="en").sort())hash.update(readFileSync(`public/locales/${locale}.json`));
const version=hash.digest("hex").slice(0,16);
writeFileSync("lib/i18n/catalogue-version.ts",`// Generated by npm run i18n:version. Keeps first paint and subsequent language switches on the same catalogue revision.\nexport const CATALOGUE_VERSION = "${version}";\n`);
console.log(`Catalogue revision ${version}`);
