// Promote an existing contract's requirements and flows into a NEW approved PRODUCTION contract.
//
// WHY THIS IS NEEDED. An app can end up with a stale production contract while all the real authoring
// happened on a guarantee contract. demo@vraelis.com/Notewell was exactly that: production v2 from July 20
// whose three flows click "Create free account", "Sign in" and "See pricing" — buttons that do not exist on
// the app, so every one timed out after 10s and the verdict was BLOCKED for reasons that say nothing about
// the app. Meanwhile guarantee v9 held 13 approved requirements and 5 flows that had actually run green.
//
// WHY A COPY AND NOT RE-DISCOVERY. runDiscovery() would crawl and re-synthesize, and the stale flows it
// would be replacing look exactly like generic AI output ("View pricing information" on a note-taking app),
// so re-running the same generator is the one approach with a known failure precedent here. The source
// contract's flows are already proven against this deployment by a completed run. Copying a proven artifact
// beats regenerating an unproven one.
//
// DRY RUN BY DEFAULT. Prints the plan and writes nothing without --apply. Refuses to run twice by checking
// for an existing production contract at or above the version it would create, because the failure mode of
// a double-run is two approved production contracts where the newest silently wins.
import { loadLocalEnv } from "../worker/preflight/local-env";
import { getSupabaseAdminClient, isDatabaseConfigured } from "../lib/supabase-admin";
import { getContract, getApprovedContract } from "../lib/v-applications";

loadLocalEnv();

const ARG = (f: string): string | null => {
  const i = process.argv.indexOf(f);
  return i > 0 && process.argv[i + 1] ? process.argv[i + 1] : null;
};
const APPLY = process.argv.includes("--apply");
const OWNER = ARG("--owner");
const APP = ARG("--app");
const FROM = ARG("--from");

// Columns that identify a row or its parent — never copied, always regenerated by the insert.
const DROP = new Set(["id", "contract_id", "created_at", "updated_at"]);
const copyRow = (r: Record<string, unknown>, contractId: string) => {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(r)) if (!DROP.has(k)) out[k] = v;
  out.contract_id = contractId;
  return out;
};

async function main() {
  if (!OWNER || !APP || !FROM) {
    console.log(`
  npx tsx scripts/preflight-promote-contract.ts --owner EMAIL --app APP_UUID --from CONTRACT_UUID [--apply]

    Copies --from's requirements and flows into a new APPROVED production contract
    for --app. Dry run unless --apply is passed.
`);
    process.exitCode = 2;
    return;
  }
  if (!isDatabaseConfigured()) {
    console.error("No database configured. Run: vercel env pull .env.local --environment=production");
    process.exitCode = 2;
    return;
  }
  const s = getSupabaseAdminClient();
  const owner = OWNER.trim().toLowerCase();

  const src = await s.from("v_production_contracts" as never)
    .select("*").eq("id", FROM).eq("user_id", owner).maybeSingle();
  if (src.error) { console.error(`source contract read failed: ${src.error.message}`); process.exitCode = 1; return; }
  const source = src.data as Record<string, unknown> | null;
  if (!source) { console.error(`no contract ${FROM} for ${owner}`); process.exitCode = 1; return; }
  if (source.application_id !== APP) {
    console.error(`contract ${FROM} belongs to application ${source.application_id}, not ${APP}`);
    process.exitCode = 1; return;
  }

  const all = await s.from("v_production_contracts" as never)
    .select("id, version, status, kind").eq("application_id", APP).order("version", { ascending: false });
  if (all.error) { console.error(`version scan failed: ${all.error.message}`); process.exitCode = 1; return; }
  const rows = (all.data as { id: string; version: number; status: string; kind: string }[]) ?? [];
  const nextVersion = Math.max(...rows.map((r) => r.version)) + 1;

  // The double-run guard. A second copy would become the newest production contract and silently take over
  // from the first, with no visible difference until someone compares flow ids.
  const already = rows.find((r) => r.kind === "production" && r.version >= nextVersion);
  if (already) {
    console.error(`refusing: production contract v${already.version} already exists at or above v${nextVersion}`);
    process.exitCode = 1; return;
  }

  const [reqQ, flowQ] = await Promise.all([
    s.from("v_contract_requirements" as never).select("*").eq("contract_id", FROM).order("order_index"),
    s.from("v_test_flows" as never).select("*").eq("contract_id", FROM).order("order_index"),
  ]);
  if (reqQ.error) { console.error(`requirements read failed: ${reqQ.error.message}`); process.exitCode = 1; return; }
  if (flowQ.error) { console.error(`flows read failed: ${flowQ.error.message}`); process.exitCode = 1; return; }
  const reqs = (reqQ.data as Record<string, unknown>[]) ?? [];
  const flows = (flowQ.data as Record<string, unknown>[]) ?? [];

  // Only flows a launch could actually select are worth copying: the run route requires enabled AND
  // review_state approved, so copying a disabled flow just recreates an ineligible row.
  const eligible = flows.filter((f) => Boolean(f.enabled) && ((f.review_state as string | undefined) ?? "approved") === "approved");

  console.log(`\nsource      v${source.version} ${source.status} kind=${source.kind}  ${FROM}`);
  console.log(`target      v${nextVersion} approved kind=production  (new)`);
  console.log(`requirements ${reqs.length} copied`);
  console.log(`flows        ${eligible.length} of ${flows.length} copied (enabled + approved only)`);
  for (const f of eligible) console.log(`             [${f.priority}] ${f.name}`);
  if (flows.length !== eligible.length) {
    for (const f of flows.filter((x) => !eligible.includes(x))) console.log(`             SKIPPED  ${f.name}  (enabled=${f.enabled} review_state=${f.review_state})`);
  }

  const before = await Promise.all([getContract(owner, APP), getApprovedContract(owner, APP)]);
  console.log(`\nbefore      page v${before[0]?.version ?? "-"}   route v${before[1]?.version ?? "-"}`);

  if (!APPLY) {
    console.log(`\nDRY RUN — nothing written. Re-run with --apply to perform it.`);
    return;
  }

  // ORDER MATTERS: the contract must exist before its children, and it is inserted APPROVED because an
  // unapproved production contract refuses every launch at a different gate (contract_not_approved).
  const ins = await s.from("v_production_contracts" as never).insert({
    application_id: APP, user_id: owner, version: nextVersion, status: "approved", kind: "production",
    source_prompt: source.source_prompt ?? null, approved_at: new Date().toISOString(),
  } as never).select("id, version").maybeSingle();
  if (ins.error || !ins.data) { console.error(`contract insert failed: ${ins.error?.message}`); process.exitCode = 1; return; }
  const created = ins.data as { id: string; version: number };
  console.log(`\ncreated contract v${created.version}  ${created.id}`);

  if (reqs.length) {
    const r = await s.from("v_contract_requirements" as never).insert(reqs.map((x) => copyRow(x, created.id)) as never);
    if (r.error) { console.error(`requirement copy failed: ${r.error.message} — contract ${created.id} left in place, delete it before retrying`); process.exitCode = 1; return; }
    console.log(`copied ${reqs.length} requirements`);
  }
  if (eligible.length) {
    const f = await s.from("v_test_flows" as never).insert(eligible.map((x) => copyRow(x, created.id)) as never);
    if (f.error) { console.error(`flow copy failed: ${f.error.message} — contract ${created.id} left in place, delete it before retrying`); process.exitCode = 1; return; }
    console.log(`copied ${eligible.length} flows`);
  }

  // VERIFY THROUGH THE REAL RESOLVERS, not by re-reading what we just wrote. The whole defect this app hit
  // was two resolvers disagreeing, so the only convincing check is that both now answer with the new
  // contract and that its flows pass the run route's own eligibility filter.
  const [page, route] = await Promise.all([getContract(owner, APP), getApprovedContract(owner, APP)]);
  console.log(`after       page v${page?.version ?? "-"}   route v${route?.version ?? "-"}   ${page?.id === route?.id ? "SAME CONTRACT" : "MISMATCH"}`);
  const check = await s.from("v_test_flows" as never)
    .select("id, name, enabled, review_state").eq("contract_id", created.id);
  const got = (check.data as Record<string, unknown>[] | null) ?? [];
  const runnable = got.filter((f) => Boolean(f.enabled) && ((f.review_state as string | undefined) ?? "approved") === "approved");
  console.log(`launchable flows on v${created.version}: ${runnable.length}`);
  process.exitCode = page?.id === route?.id && runnable.length > 0 ? 0 : 1;
}

void main();
