import assert from "node:assert/strict";
import { evaluateRecording, parseRecording, covers, validateRequirement, type Recording } from "../lib/recorded-verification/evaluate";
import { exampleRecording, EXAMPLE_REQUIREMENT } from "../lib/recorded-verification/examples";
let passed = 0;
const test = (name: string, run: () => void) => { run(); passed++; console.log(`PASS ${name}`); };
const evaluate = (r: Recording) => evaluateRecording(parseRecording(JSON.stringify(r)), EXAMPLE_REQUIREMENT);
const changed = (fn: (r: Recording) => void) => { const r = exampleRecording("corrected"); fn(r); return r; };
test("corrected recording satisfies the approved reported-state criteria", () => assert.equal(evaluate(exampleRecording("corrected")).verdict, "passed"));
test("control success without device completion is a failure with full capture", () => assert.equal(evaluate(exampleRecording("broken")).findings.find(f => f.id === "device")?.verdict, "failed"));
test("unintended second-asset mutation is identified", () => assert.equal(evaluate(exampleRecording("broken")).findings.find(f => f.id === "unchanged:Robot B")?.verdict, "failed"));
test("missing telemetry is inconclusive, never a pass", () => assert.equal(evaluate(exampleRecording("missing")).verdict, "inconclusive"));
test("a stale completion before the request cannot establish success", () => assert.equal(evaluate(changed(r => { r.events.find(e => e.id === "device-completed")!.timeMs = r.window.startMs; })).verdict, "failed"));
test("completion for the wrong asset cannot establish success", () => assert.equal(evaluate(changed(r => { r.events.find(e => e.id === "device-completed")!.assetId = "Robot C"; })).verdict, "failed"));
test("completion for the wrong task cannot establish success", () => assert.equal(evaluate(changed(r => { r.events.find(e => e.id === "device-completed")!.taskId = "old-task"; })).verdict, "failed"));
test("duplicate requests for a reused task identity are inconclusive", () => assert.equal(evaluate(changed(r => { r.events.push({ ...r.events.find(e => e.id === "requested")!, id: "request-again" }); })).verdict, "inconclusive"));
test("late completion fails the approved timing requirement", () => assert.equal(evaluate(changed(r => { r.events.find(e => e.id === "device-completed")!.timeMs = r.window.endMs; })).verdict, "failed"));
test("control completion before device completion is contradictory", () => assert.equal(evaluate(changed(r => { r.events.find(e => e.id === "ui-completed")!.timeMs -= 1000; })).findings.find(f => f.id === "order")?.verdict, "failed"));
test("failure after a completion still contradicts the task outcome", () => assert.equal(evaluate(changed(r => { r.events.push({ id: "device-failure", source: "device", assetId: "Robot A", taskId: "task-104", state: "failed", timeMs: r.window.startMs + 7000 }); })).verdict, "failed"));
test("a failed service response is not hidden by an accepted event", () => assert.equal(evaluate(changed(r => { r.events.push({ id: "service-failure", source: "service", assetId: "Robot A", taskId: "task-104", state: "failed", timeMs: r.window.startMs + 3000 }); })).verdict, "failed"));
test("short capture without completion cannot support a negative assertion", () => {
 const r = changed(r => { r.events = r.events.filter(e => e.id !== "device-completed" && e.id !== "b-final"); r.coverage = r.coverage.map(c => c.source === "device" ? { ...c, endMs: r.window.startMs + 5000 } : c); });
 assert.equal(evaluate(r).findings.find(f => f.id === "device")?.verdict, "inconclusive");
});
test("coverage gaps are not merged into uninterrupted evidence", () => { const r=exampleRecording("corrected");r.coverage=[{source:"device",startMs:r.window.startMs,endMs:r.window.startMs+3000},{source:"device",startMs:r.window.startMs+5000,endMs:r.window.endMs}];assert.equal(covers(r,"device",r.window.startMs,r.window.endMs),false); });
test("overlapping capture intervals cover the complete requested period", () => {const r=exampleRecording("corrected");r.coverage=[{source:"device",startMs:r.window.startMs,endMs:r.window.startMs+7000},{source:"device",startMs:r.window.startMs+6000,endMs:r.window.endMs}];assert.equal(covers(r,"device",r.window.startMs,r.window.endMs),true);});
test("no baseline makes unchanged-state evaluation inconclusive", () => assert.equal(evaluate(changed(r => { r.events = r.events.filter(e => e.id !== "b-baseline"); })).verdict, "inconclusive"));
test("a missing request cannot become a pass from successful-looking results", () => assert.equal(evaluate(changed(r => { r.events = r.events.filter(e => e.id !== "requested"); })).verdict, "inconclusive"));
test("unsupported states are rejected", () => { const r=exampleRecording("corrected");assert.throws(()=>parseRecording(JSON.stringify(r).replace('"state":"accepted"','"state":"looks-good"'))); });
test("duplicate evidence IDs are rejected", () => assert.throws(() => evaluate(changed(r => { r.events.push({...r.events[0]}); }))));
test("undeclared clock domains are rejected", () => assert.throws(() => parseRecording(JSON.stringify(exampleRecording("corrected")).replace('"unix-ms"','"device-clock"'))));
test("events outside coverage are rejected", () => assert.throws(() => evaluate(changed(r => {r.coverage=r.coverage.filter(c=>c.source!=="device");}))));
test("invalid completion thresholds are rejected", () => assert.throws(() => validateRequirement({...EXAMPLE_REQUIREMENT,completionWithinMs:NaN})));
test("target asset cannot also be an unchanged asset", () => assert.throws(() => validateRequirement({...EXAMPLE_REQUIREMENT,untouchedAssetIds:["Robot A"]})));
test("the report retains the exact requirement and event references", () => {const result=evaluate(exampleRecording("corrected"));assert.deepEqual(result.requirement,EXAMPLE_REQUIREMENT);assert.deepEqual(result.findings.find(f=>f.id==='order')?.eventIds,['accepted','device-completed','ui-completed']);});
test("conflicting observations at the baseline time cannot establish unchanged state", () => assert.equal(evaluate(changed(r => {r.events.push({...r.events.find(e=>e.id==="b-baseline")!,id:"b-conflict",state:"accepted"});})).verdict,"inconclusive"));
test("timestamp arithmetic cannot exceed safe precision", () => {const r=exampleRecording("corrected");const delta=Number.MAX_SAFE_INTEGER-r.window.endMs;r.window.startMs+=delta;r.window.endMs+=delta;for(const c of r.coverage){c.startMs+=delta;c.endMs+=delta;}for(const e of r.events)e.timeMs+=delta;assert.throws(()=>evaluateRecording(parseRecording(JSON.stringify(r)),{...EXAMPLE_REQUIREMENT,completionWithinMs:3600000}));});
test("successful events in partial capture cannot hide unobserved adverse states", () => {const r=changed(r=>{r.coverage=r.coverage.flatMap(c=>c.source==="service"?[{...c,endMs:r.window.startMs+2000},{...c,startMs:r.window.startMs+4000}]:[c]);});assert.equal(evaluate(r).findings.find(f=>f.id==="service")?.verdict,"inconclusive");});
test("UTF-8 byte-order-mark recordings parse without altering the source text",()=>{const raw="\uFEFF"+JSON.stringify(exampleRecording("corrected"));assert.equal(parseRecording(raw).runId,"simulation-corrected");assert.equal(raw.charCodeAt(0),0xfeff);});
console.log(`${passed} recorded-verification checks passed`);
